### ISSUE TITLE
Feature Request: 1-phase charging

### ISSUE THREAD

**Issue by flicksolutions** [goecharger/go-eCharger-API-v1#9]
Thank you for creating the api!

It would be great if I could choose on how many phases (1-3) I want to load my car. Is it even possible hardware-wise or do I have to figure out something else?

**Comment by peterpoetzi** [comment]
It is not possible with the current hardware because it only has a 4-pole contactor, which will always connect all three phases as well as the neutral conductor, even when you only connected it to a single phase outlet. It is however possible, to disconnect the phases L2 and L3 before the go-eCharger (for safe operation, disconnect the go-eCharger completely and reconnect with our without L2 and L3). It is not possible to charge with 2 phases connected only, this will lead to an error.
